import { makeStyles } from '@mui/styles';
import type { Theme } from '@mui/material/styles';

export const useStyles = makeStyles((theme: Theme) => ({
  root: {
    minHeight: '100vh',
    backgroundColor: theme.palette.slate[100],
    display: 'flex',
    flexDirection: 'column',
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 32px',
    [theme.breakpoints.down('sm')]: {
      padding: '12px 20px',
    },
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  brandLogo: {
    width: '44px',
    height: '44px',
    borderRadius: '10px',
    backgroundColor: theme.palette.navy[800],
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
  },
  brandLogoImg: {
    width: '32px',
    height: '32px',
    objectFit: 'cover' as const,
  },
  brandTitle: {
    fontWeight: 800,
    fontSize: '16px',
    color: theme.palette.navy[800],
    lineHeight: 1.1,
  },
  brandSubtitle: {
    fontSize: '9px',
    color: theme.palette.slate[500],
    textTransform: 'uppercase' as const,
    letterSpacing: '0.1em',
  },
  langSelector: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    cursor: 'pointer',
    color: theme.palette.slate[500],
    borderRadius: '6px',
    padding: '4px 8px',
    '&:hover': { backgroundColor: theme.palette.slate[200] },
    '&:focus-visible': { outline: `2px solid ${theme.palette.navy[800]}`, outlineOffset: '1px' },
  },
  langFlag: {
    fontSize: '16px',
    lineHeight: 1,
  },
  langText: {
    fontSize: '13px',
    fontWeight: 600,
    color: theme.palette.navy[800],
  },
  centerContent: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
  },
  card: {
    backgroundColor: theme.palette.bg.paper,
    borderRadius: '16px',
    border: `1px solid ${theme.palette.slate[200]}`,
    boxShadow: '0 4px 24px rgba(0,0,0,0.06)',
    padding: '36px 40px',
    width: '100%',
    maxWidth: '460px',
    [theme.breakpoints.down('sm')]: {
      padding: '28px 24px',
      maxWidth: '100%',
    },
  },
  secureBadge: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: theme.palette.slate[100],
    border: `1px solid ${theme.palette.slate[200]}`,
    borderRadius: '20px',
    padding: '4px 12px',
    marginBottom: '20px',
  },
  secureBadgeText: {
    fontSize: '11px',
    fontWeight: 600,
    color: theme.palette.slate[500],
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  cardTitle: {
    fontWeight: 700,
    fontSize: '22px',
    color: theme.palette.navy[800],
    marginBottom: '4px',
  },
  cardSubtitle: {
    fontSize: '14px',
    color: theme.palette.slate[500],
    marginBottom: '24px',
  },
  fieldLabel: {
    display: 'block',
    fontSize: '13px',
    fontWeight: 600,
    color: theme.palette.navy[800],
    marginBottom: '6px',
  },
  fieldLabelRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '6px',
  },
  forgotLink: {
    fontSize: '12px !important',
    fontWeight: '600 !important',
    color: `${theme.palette.slate[500]} !important`,
    textDecoration: 'none !important',
    '&:hover': { color: `${theme.palette.navy[800]} !important` },
  },
  inputWrapper: {
    marginBottom: '16px',
  },
  signInBtn: {
    width: '100%',
    backgroundColor: `${theme.palette.navy[800]} !important`,
    color: '#ffffff !important',
    fontWeight: '700 !important',
    padding: '12px 0 !important',
    fontSize: '14px !important',
    borderRadius: '10px !important',
    marginBottom: '0',
    '&:hover': { backgroundColor: `${theme.palette.navy[900]} !important` },
    '&:focus-visible': { outline: `3px solid ${theme.palette.teal[400]}`, outlineOffset: '2px' },
  },
  ssoBtn: {
    width: '100%',
    border: `1.5px solid ${theme.palette.slate[300]} !important`,
    color: `${theme.palette.navy[800]} !important`,
    fontWeight: '600 !important',
    padding: '11px 0 !important',
    fontSize: '14px !important',
    borderRadius: '10px !important',
    '&:hover': { backgroundColor: `${theme.palette.slate[50]} !important`, borderColor: `${theme.palette.slate[400]} !important` },
    '&:focus-visible': { outline: `3px solid ${theme.palette.navy[800]}`, outlineOffset: '2px' },
  },
  dividerText: {
    fontSize: '11px',
    color: theme.palette.slate[400],
    textTransform: 'uppercase' as const,
    letterSpacing: '0.08em',
  },
  securityNote: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    marginTop: '16px',
  },
  securityNoteText: {
    fontSize: '11px',
    color: theme.palette.slate[400],
  },
  footer: {
    textAlign: 'center' as const,
    padding: '16px 32px 24px',
  },
  footerText: {
    fontSize: '13px',
    color: theme.palette.slate[500],
    marginBottom: '14px',
  },
  footerLink: {
    color: '#2563eb !important',
    fontWeight: '600 !important',
    textDecoration: 'underline !important',
    textDecorationColor: '#2563eb !important',
    '&:hover': { color: '#1d4ed8 !important' },
  },
  gdprNotice: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
    backgroundColor: '#eff6ff',
    border: '1px solid #bfdbfe',
    borderRadius: '10px',
    padding: '14px 16px',
    marginBottom: '16px',
    textAlign: 'left' as const,
    maxWidth: '460px',
    margin: '14px auto 16px',
  },
  gdprIcon: {
    fontSize: '18px !important',
    color: '#3b82f6 !important',
    flexShrink: 0,
    marginTop: '1px',
  },
  gdprText: {
    fontSize: '12px !important',
    color: '#374151 !important',
    lineHeight: '1.6 !important',
  },
  footerSmall: {
    fontSize: '12px !important',
    color: theme.palette.slate[300],
    marginTop: '6px',
  },
  footerSmallLink: {
    color: `${theme.palette.slate[400]} !important`,
    textDecoration: 'none !important',
    fontSize: '12px !important',
    '&:hover': { textDecoration: 'underline !important' },
  },
}));
