import { makeStyles } from '@mui/styles';
import type { Theme } from '@mui/material/styles';

export const useStyles = makeStyles((theme: Theme) => ({
  // ─── Page layout (mirrors Vacancy) ─────────────────────────────────────────
  pageHeader: {
    backgroundColor: '#ffffff',
    borderBottom: '1px solid #f3f4f6',
    padding: '0 24px',
    flexShrink: 0,
    [theme.breakpoints.down('sm')]: {
      padding: '0 12px',
    },
  },
  pageContent: {
    flex: 1,
    overflowY: 'auto' as const,
    padding: '24px',
    [theme.breakpoints.down('sm')]: {
      padding: '12px',
    },
  },

  // ─── Application form outer card (Figma spec) ────────────────────────────────
  appFormCard: {
    border: '1px solid #E2E8F0',
    borderRadius: '12px !important',
    boxShadow: 'none !important' as any,
    marginBottom: '14px',
    overflow: 'hidden',
  },
  appFormHeader: {
    padding: '16px 20px 17px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  appFormBody: {
    padding: '20px',
    [theme.breakpoints.down('sm')]: {
      padding: '14px',
    },
  },
  appFormTitle: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '600 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#1E293B !important',
    margin: '0 !important',
  },
  appFormSubtitle: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '12px !important',
    lineHeight: '16px !important',
    color: '#94A3B8 !important',
    paddingTop: '2px',
  },
  // ─── Application Summary card (Figma spec) ───────────────────────────────────
  summaryCard: {
    border: '1px solid #E2E8F0',
    borderRadius: '12px !important',
    boxShadow: 'none !important' as any,
    marginBottom: '14px',
    overflow: 'hidden',
  },
  summaryHeader: {
    padding: '16px 20px 17px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  summaryTitle: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '600 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#1E293B !important',
    margin: '0 !important',
  },
  summarySubtitle: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '12px !important',
    lineHeight: '16px !important',
    color: '#94A3B8 !important',
    paddingTop: '2px',
  },
  summaryBody: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap' as const,
    alignItems: 'flex-start',
    gap: '24px',
    padding: '20px',
    borderTop: '1px solid #F1F5F9',
  },
  summaryCol: {
    flex: '1 1 calc(33.333% - 16px)',
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    [theme.breakpoints.down('sm')]: {
      flex: '1 1 calc(50% - 12px)',
    },
  },
  summaryLabel: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '600 !important' as any,
    fontSize: '10px !important',
    lineHeight: '15px !important',
    letterSpacing: '0.5px !important',
    color: '#94A3B8 !important',
    paddingBottom: '8px',
    textTransform: 'none' as const,
  },
  summaryDateRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '6px',
    fontFamily: '"Roboto", sans-serif',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '20px',
    color: '#334155',
    '& > span': { fontFamily: 'inherit', fontWeight: 'inherit', fontSize: 'inherit', lineHeight: 'inherit' },
    '& .MuiSvgIcon-root': {
      fontSize: '14px',
      width: '12.5px',
      height: '12px',
      color: '#94A3B8',
    },
  },
  statusPillBase: {
    boxSizing: 'border-box' as const,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '4px',
    padding: '3px 11px',
    borderRadius: '9999px',
    fontFamily: '"Roboto", sans-serif',
    fontWeight: 500,
    fontSize: '11px',
    lineHeight: '20px',
    '& .MuiSvgIcon-root': {
      fontSize: '12px',
      width: '11.45px',
      height: '11px',
    },
  },
  statusPillYes: {
    backgroundColor: '#ECFDF5',
    border: '1px solid #A7F3D0',
    color: '#047857',
    '& .MuiSvgIcon-root': { color: '#047857' },
  },
  statusPillPending: {
    backgroundColor: '#FFFBEB',
    border: '1px solid #FDE68A',
    color: '#B45309',
    '& .MuiSvgIcon-root': { color: '#B45309' },
  },
  statusPillFresh: {
    boxSizing: 'border-box' as const,
    display: 'inline-flex',
    alignItems: 'center',
    padding: '5px 13px',
    backgroundColor: '#F0FDFA',
    border: '1px solid #99F6E4',
    borderRadius: '9999px',
    fontFamily: '"Roboto", sans-serif',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '16px',
    color: '#0F766E',
  },
  // Section divider (between sub-sections inside the form card)
  formDivider: {
    width: '100%',
    borderTop: '1px solid #F1F5F9',
    marginTop: '32px',
    marginBottom: '32px',
  },

  // ─── Candidate header card (Figma spec) ──────────────────────────────────────
  headerCard: {
    padding: '20px',
    marginBottom: '16px',
    border: '1px solid #E2E8F0',
    borderRadius: '12px !important',
    boxShadow: 'none !important' as any,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap' as const,
    alignItems: 'flex-start',
    gap: '20px',
  },
  headerLeft: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: '1 1 545px',
    minWidth: 0,
    gap: '14px',
  },
  headerFieldGrid: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap' as const,
    alignItems: 'flex-start',
    gap: '16px',
    width: '100%',
  },
  headerField: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: '1 1 calc(50% - 8px)',
    minWidth: 0,
    [theme.breakpoints.down('sm')]: {
      flex: '1 1 100%',
    },
  },
  headerFieldFull: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: '1 1 100%',
    minWidth: 0,
  },
  headerFieldLabel: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '600 !important' as any,
    fontSize: '10px !important',
    lineHeight: '15px !important',
    letterSpacing: '0.5px !important',
    color: '#94A3B8 !important',
    paddingBottom: '4px',
    textTransform: 'none' as const,
  },
  headerFieldValue: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '500 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#1E293B !important',
    letterSpacing: '0 !important',
  },
  headerFieldValueMono: {
    fontFamily: '"Roboto Mono", monospace !important',
    fontWeight: '400 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#1E293B !important',
    letterSpacing: '0 !important',
  },
  headerFieldValueRow: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '6px',
    fontFamily: '"Roboto", sans-serif',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '20px',
    color: '#334155',
    '& > span': {
      fontFamily: '"Roboto", sans-serif',
      fontWeight: 400,
      fontSize: '14px',
      lineHeight: '20px',
    },
    '& .MuiSvgIcon-root': {
      fontSize: '14px',
      width: '12.5px',
      height: '12px',
      color: '#94A3B8',
    },
  },
  headerFieldValueEmail: {
    color: '#34D399 !important',
  },
  mapPlaceholder: {
    boxSizing: 'border-box' as const,
    width: '528px',
    maxWidth: '100%',
    height: '182px',
    border: '1px solid #C9C9C9',
    borderRadius: '7px',
    backgroundColor: theme.palette.slate[100],
    backgroundImage: 'linear-gradient(135deg, #e8edf2 25%, #d4dce6 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flex: '0 1 528px',
    [theme.breakpoints.down('md')]: { display: 'none' },
  },
  mapPlaceholderText: {
    fontSize: '12px',
    color: theme.palette.slate[400],
  },

  // ─── Tabs (Figma spec) ───────────────────────────────────────────────────────
  tabs: {
    minHeight: '42px !important',
    '& .MuiTab-root': {
      fontFamily: '"Roboto", sans-serif',
      fontSize: '12px !important',
      fontWeight: '500 !important' as any,
      lineHeight: '16px !important',
      textTransform: 'none' as const,
      color: '#9CA3AF !important',
      minWidth: 0,
      minHeight: '42px !important',
      padding: '12px 16px 14px !important',
      gap: '8px',
    },
    '& .MuiTab-iconWrapper': {
      color: '#9CA3AF',
      fontSize: '14px',
      width: '14px',
      height: '14px',
      margin: '0 !important',
    },
    '& .Mui-selected': {
      color: '#0F1F3D !important',
    },
    '& .Mui-selected .MuiTab-iconWrapper': {
      color: '#0F1F3D',
    },
    '& .MuiTabs-indicator': {
      backgroundColor: '#0F1F3D',
      height: '2px',
    },
  },
  // ─── Candidate strip (top header below tabs) ─────────────────────────────────
  candidateStrip: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '20px',
    padding: '16px 24px 17px',
    backgroundColor: '#FFFFFF',
    borderBottom: '1px solid #f3f4f6',
    [theme.breakpoints.down('sm')]: {
      padding: '12px 16px',
      gap: '12px',
    },
  },
  candidateStripAvatar: {
    width: '44px !important',
    height: '44px !important',
    [theme.breakpoints.up('sm')]: {
      width: '56px !important',
      height: '56px !important',
    },
    borderRadius: '12px !important',
    background: 'linear-gradient(135deg, #0F1F3D 0%, #1E3A6E 100%) !important',
    color: '#FFFFFF !important',
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '700 !important' as any,
    fontSize: '18px !important',
    lineHeight: '28px !important',
    flexShrink: 0,
  },
  candidateStripBody: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    flex: 1,
    minWidth: 0,
    gap: '6px',
  },
  candidateStripTitleRow: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    gap: '12px',
  },
  candidateStripName: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '600 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#1E293B !important',
    margin: '0 !important',
  },
  candidateStripStatus: {
    boxSizing: 'border-box' as const,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '3px 11px',
    backgroundColor: '#F0F9FF',
    border: '1px solid #BAE6FD',
    borderRadius: '9999px',
    fontFamily: '"Roboto", sans-serif',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '16px',
    color: '#0369A1',
  },
  candidateStripStatusDot: {
    width: '6px',
    height: '6px',
    borderRadius: '9999px',
    backgroundColor: '#38BDF8',
    flexShrink: 0,
  },
  candidateStripMeta: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap' as const,
    alignItems: 'center',
    gap: '16px',
    [theme.breakpoints.down('sm')]: {
      gap: '8px',
    },
  },
  candidateStripMetaItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '6px',
    fontFamily: '"Roboto", sans-serif',
    fontWeight: 400,
    fontSize: '12px',
    lineHeight: '16px',
    color: '#6B7280',
    '& .MuiSvgIcon-root': {
      fontSize: '14px',
      width: '12.5px',
      height: '12px',
      color: '#9CA3AF',
    },
  },
  candidateStripMetaItemMono: {
    fontFamily: '"Roboto Mono", monospace !important',
    color: '#9CA3AF !important',
    '& .MuiSvgIcon-root': { color: '#D1D5DB !important' },
  },

  // ─── Section cards (legacy, used for Summary/Interview/Offer) ────────────────
  sectionCard: {
    padding: '16px 20px',
    marginBottom: '14px',
    border: `1px solid ${theme.palette.slate[200]}`,
    borderRadius: '12px !important',
    boxShadow: 'none !important' as any,
  },
  // ─── Form sub-section (inside the big Application Form card) ─────────────────
  formSection: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  sectionHeaderRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '16px',
    width: '100%',
  },
  sectionIconBox: {
    width: '28px',
    height: '28px',
    borderRadius: '8px',
    backgroundColor: '#F0FDFA',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    '& .MuiSvgIcon-root': {
      fontSize: '14px',
      color: '#34D399',
    },
  },
  sectionTitle: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '600 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#334155 !important',
  },
  formGrid: {
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap' as const,
    alignItems: 'flex-start',
    gap: '20px',
    width: '100%',
  },
  formCol6: {
    flex: '1 1 calc(50% - 10px)',
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    [theme.breakpoints.down('sm')]: {
      flex: '1 1 100%',
    },
  },
  formCol12: {
    flex: '1 1 100%',
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },

  // ─── Fields (Figma spec) ─────────────────────────────────────────────────────
  fieldLabel: {
    display: 'block',
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '500 !important' as any,
    fontSize: '12px !important',
    lineHeight: '16px !important',
    color: '#475569 !important',
    paddingBottom: '6px',
    textTransform: 'none' as const,
    letterSpacing: '0 !important',
  },
  requiredStar: {
    color: '#F87171',
    marginLeft: '2px',
    fontFamily: '"Roboto", sans-serif',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '16px',
  },
  questionLabel: {
    display: 'block',
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '500 !important' as any,
    fontSize: '12px !important',
    lineHeight: '16px !important',
    color: '#475569 !important',
    paddingBottom: '6px',
    width: '100%',
  },
  fieldBox: {
    boxSizing: 'border-box' as const,
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '9px 13px',
    backgroundColor: '#FFFFFF',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    '& > .MuiTypography-root': { margin: 0 },
  },
  fieldValue: {
    display: 'block',
    margin: '0 !important',
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#334155 !important',
  },
  textAreaBox: {
    boxSizing: 'border-box' as const,
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '9px 13px',
    backgroundColor: '#FFFFFF',
    minHeight: '78px',
    width: '100%',
    display: 'flex',
    alignItems: 'flex-start',
    '& > .MuiTypography-root': { margin: 0 },
  },
  textAreaValue: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#334155 !important',
  },
  charCount: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '11px !important',
    lineHeight: '16px !important',
    color: '#94A3B8 !important',
    paddingTop: '4px',
  },
  dateFieldBox: {
    boxSizing: 'border-box' as const,
    border: '1px solid #E2E8F0',
    borderRadius: '8px',
    padding: '9px 13px',
    backgroundColor: '#FFFFFF',
    minHeight: '38px',
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  datePickerField: {
    width: '100%',
    '& .MuiOutlinedInput-root': {
      height: '38px',
      backgroundColor: '#FFFFFF',
      borderRadius: '8px',
      fontFamily: '"Roboto", sans-serif',
      fontWeight: 400,
      fontSize: '14px',
      lineHeight: '20px',
      color: '#334155',
      paddingRight: '8px',
    },
    '& .MuiOutlinedInput-input': {
      padding: '9px 13px !important',
      fontSize: '14px',
      fontFamily: '"Roboto", sans-serif',
      color: '#334155',
    },
    '& .MuiOutlinedInput-notchedOutline': {
      borderColor: '#E2E8F0 !important',
      borderWidth: '1px !important',
    },
    '&:hover .MuiOutlinedInput-notchedOutline': { borderColor: '#CBD5E1 !important' },
    '& .Mui-focused .MuiOutlinedInput-notchedOutline': {
      borderColor: '#94A3B8 !important',
      borderWidth: '1px !important',
    },
  },
  dropdownSelect: {
    width: '100%',
    height: '36px',
    backgroundColor: '#FFFFFF',
    borderRadius: '8px !important',
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '14px !important',
    lineHeight: '16px !important',
    color: '#334155 !important',
    '& .MuiOutlinedInput-notchedOutline': {
      borderColor: '#E2E8F0 !important',
      borderWidth: '1px !important',
    },
    '&:hover .MuiOutlinedInput-notchedOutline': {
      borderColor: '#CBD5E1 !important',
    },
    '&.Mui-focused .MuiOutlinedInput-notchedOutline': {
      borderColor: '#94A3B8 !important',
      borderWidth: '1px !important',
    },
    '& .MuiSelect-select': {
      padding: '9px 13px !important',
      minHeight: '0 !important',
      display: 'flex',
      alignItems: 'center',
      fontFamily: '"Roboto", sans-serif',
      fontWeight: 400,
      fontSize: '14px',
      lineHeight: '16px',
      color: '#334155',
      boxSizing: 'border-box',
    },
    '& .MuiSelect-icon': {
      color: '#334155',
      right: '10px',
      fontSize: '18px',
    },
  },
  fieldHint: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '11px !important',
    lineHeight: '16px !important',
    color: '#94A3B8 !important',
    paddingTop: '4px',
    fontStyle: 'italic' as const,
  },

  // ─── Yes / No toggles (Figma spec) ───────────────────────────────────────────
  yesNoGroup: {
    display: 'inline-flex',
    gap: '8px',
  },
  yesNoBtnBase: {
    boxSizing: 'border-box' as const,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
    padding: '9px 17px',
    height: '34px',
    borderRadius: '8px',
    cursor: 'pointer',
    fontFamily: '"Roboto", sans-serif',
    fontWeight: 500,
    fontSize: '12px',
    lineHeight: '16px',
    outline: 'none',
  },
  yesActiveBtn: {
    backgroundColor: '#ECFDF5',
    border: '1px solid #6EE7B7',
    color: '#047857',
  },
  yesInactiveBtn: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #E2E8F0',
    color: '#64748B',
    '&:hover': { backgroundColor: '#F8FAFC' },
  },
  noActiveBtn: {
    backgroundColor: '#FEF2F2',
    border: '1px solid #FCA5A5',
    color: '#DC2626',
  },
  noInactiveBtn: {
    backgroundColor: '#FFFFFF',
    border: '1px solid #E2E8F0',
    color: '#64748B',
    '&:hover': { backgroundColor: '#F8FAFC' },
  },
  radioDotBase: {
    boxSizing: 'border-box' as const,
    width: '14px',
    height: '14px',
    borderRadius: '9999px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    fontSize: '8px',
    fontWeight: 700,
    lineHeight: 1,
    color: '#FFFFFF',
  },
  radioFilled: {
    backgroundColor: '#10B981',
    border: '1px solid #10B981',
  },
  radioFilledRed: {
    backgroundColor: '#F87171',
    border: '1px solid #F87171',
  },
  radioEmpty: {
    backgroundColor: 'transparent',
    border: '1px solid #CBD5E1',
  },

  // ─── Employer card (legacy — kept for reference) ──────────────────────────────
  employerCard: {
    border: `1px solid ${theme.palette.slate[200]}`,
    borderRadius: '8px',
    padding: '12px 14px',
    marginBottom: '10px',
    '&:last-child': { marginBottom: 0 },
  },
  employerCardTitle: {
    fontSize: '11px',
    fontWeight: 700,
    color: theme.palette.info.main,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.04em',
    marginBottom: '10px',
  },

  // ─── Interview / Offer table cards (Figma spec) ──────────────────────────────
  tableCard: {
    border: '1px solid #E2E8F0',
    borderRadius: '12px !important',
    boxShadow: 'none !important' as any,
    marginBottom: '14px',
    overflow: 'hidden',
  },
  tableCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 20px 17px',
  },
  tableCardTitleBlock: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  tableCardTitle: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '600 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#1E293B !important',
    margin: '0 !important',
  },
  tableCardSubtitle: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '12px !important',
    lineHeight: '16px !important',
    color: '#94A3B8 !important',
    paddingTop: '2px',
  },
  addBtn: {
    boxSizing: 'border-box' as const,
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '7px 13px !important',
    minWidth: '0 !important',
    height: '30px',
    backgroundColor: '#F0FDFA !important',
    border: '1px solid #99F6E4 !important',
    borderRadius: '8px !important',
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '12px !important',
    lineHeight: '16px !important',
    color: '#34D399 !important',
    textTransform: 'none' as const,
    '& .MuiSvgIcon-root, & .MuiButton-startIcon .MuiSvgIcon-root': {
      fontSize: '14px',
      color: '#34D399',
      width: '12.5px',
      height: '12px',
    },
    '&:hover': { backgroundColor: '#CCFBF1 !important' },
  },
  // Table itself
  appTable: {
    width: '100%',
    '& .MuiTableHead-root .MuiTableRow-root': {
      backgroundColor: 'rgba(248, 250, 252, 0.7)',
    },
    '& .MuiTableCell-head': {
      fontFamily: '"Roboto", sans-serif',
      fontWeight: 600,
      fontSize: '11px',
      lineHeight: '20px',
      letterSpacing: '0.55px',
      color: '#94A3B8',
      padding: '12px 16px',
      borderBottom: '1px solid #F1F5F9',
    },
    '& .MuiTableCell-body': {
      fontFamily: '"Roboto", sans-serif',
      fontWeight: 400,
      fontSize: '12px',
      lineHeight: '16px',
      color: '#334155',
      padding: '12px 16px',
      borderBottom: '1px solid #F1F5F9',
    },
  },
  tableRow: {
    '&:last-child td': { borderBottom: 'none' },
  },
  tableCellRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    '& .MuiSvgIcon-root': {
      fontSize: '14px',
      color: '#94A3B8',
      width: '12.5px',
      height: '12px',
    },
  },

  // ─── Source of Application card (Figma spec) ─────────────────────────────────
  sourceCard: {
    border: '1px solid #E2E8F0',
    borderRadius: '12px !important',
    boxShadow: 'none !important' as any,
    marginBottom: '14px',
    overflow: 'hidden',
  },
  sourceHeader: {
    padding: '16px 20px 17px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  sourceTitle: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '600 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#1E293B !important',
    margin: '0 !important',
  },
  sourceBody: {
    padding: '20px',
    borderTop: '1px solid #F1F5F9',
  },
  sourceRow: {
    boxSizing: 'border-box' as const,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: '12px',
    padding: '13px',
    backgroundColor: 'rgba(248, 250, 252, 0.7)',
    border: '1px solid #F1F5F9',
    borderRadius: '8px',
    minHeight: '58px',
  },
  sourceIcon: {
    width: '32px',
    height: '32px',
    borderRadius: '8px',
    backgroundColor: '#F0FDFA',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    '& .MuiSvgIcon-root': {
      fontSize: '14px',
      color: '#34D399',
    },
  },
  sourceText: {
    fontFamily: '"Roboto", sans-serif !important',
    fontWeight: '400 !important' as any,
    fontSize: '14px !important',
    lineHeight: '20px !important',
    color: '#1E293B !important',
  },

  // ─── Empty tab ────────────────────────────────────────────────────────────────
  emptyTab: {
    textAlign: 'center' as const,
    padding: '48px 0',
    color: theme.palette.slate[400],
    fontSize: '13px',
  },
}));
